"""processテーブルの追加

Revision ID: 49bd665a01cd
Revises: 1f7ed1f5bfd7
Create Date: 2023-12-15 07:09:26.386446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bd665a01cd'
down_revision = '1f7ed1f5bfd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('termination_flag', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    # ### end Alembic commands ###
