"""indexの削除

Revision ID: 4a018406637c
Revises: ae9fb8556582
Create Date: 2023-12-15 10:10:20.979220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a018406637c'
down_revision = 'ae9fb8556582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
