"""empty message

Revision ID: 832359ae82bc
Revises: 2e469493bcfb
Create Date: 2023-12-15 12:06:00.483023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832359ae82bc'
down_revision = '2e469493bcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depth_level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('create_at')
        batch_op.drop_column('depth_level')

    # ### end Alembic commands ###
