"""test2_migration

Revision ID: f8afa49eb502
Revises: 5f45182a736f
Create Date: 2023-12-09 07:27:30.232008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8afa49eb502'
down_revision = '5f45182a736f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=240),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=24),
               type_=mysql.VARCHAR(length=240),
               existing_nullable=False)

    # ### end Alembic commands ###
