# ベースイメージ
FROM mysql/mysql-server:8.0

# 環境変数の設定
ENV TZ=JST

# ログディレクトリの作成と権限設定
RUN mkdir /var/log/mysql \
  && chown mysql:mysql /var/log/mysql \
  && chmod 777 /var/log/mysql

# ポートの公開
EXPOSE 3306

# MySQLは親イメージのCMDを使用
