# ベースイメージ
FROM mysql/mysql-server:8.0

# 環境変数の設定
ENV TZ=UTC

# ログディレクトリの作成と権限設定
RUN mkdir /var/log/mysql \
  && chown mysql:mysql /var/log/mysql \
  && chmod 777 /var/log/mysql

# タイムゾーンの設定
RUN apt-get install -y tzdata && \ ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# ポートの公開
EXPOSE 3306

# MySQLは親イメージのCMDを使用
